version: '3.7'

services:
  frontend:
    restart: always
    build: 
        context: frontend
    container_name: docker-m347-frontend
    env_file: .env
    depends_on:
      - backenduser
      - backendblog
    ports:
      - 8000:80
      - 8001:443
    labels:
      kompose.image-pull-policy: "Always"
      kompose.service.type: "NodePort"
      kompose.service.nodeport.port: "30081"
  backendblog:
    restart: always
    build:
     context: backend
    container_name: docker-m347-backend-blog
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
    depends_on:
      - db
    labels:
      kompose.image-pull-policy: "Always"
      kompose.service.type: "NodePort"
      kompose.service.nodeport.port: "30080"
  backenduser:
    restart: always
    build:
     context: backend
    container_name: docker-m347-backend-user
    ports:
      - 8081:8080
    environment:
      - DB_HOST=db
    depends_on:
      - db
    labels:
      kompose.image-pull-policy: "Always"
      kompose.service.type: "NodePort"
      kompose.service.nodeport.port: "30080"

  db:
    restart: always
    image: 'postgres:10-alpine'
    container_name: db_m347_JaSchLuSch
    expose:
    - 5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
  


